language: ruby
services:
  - redis
env:
  - DB=sqlite
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake
before_script:
  - sleep 10
  - cp config/database.yml.ci config/database.yml
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
bundler_args: --binstubs=./bundler_stubs
