default: &default
  adapter: sqlite3
  encoding: unicode

development:
  <<: *default
  database: db/shortener_development.sqlite3

test:
  <<: *default
  database: db/shortener_test.sqlite3

production:
  <<: *default
  database: db/shortener_production.sqlite3
