# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
default: &default
  base_url: http://localhost:3000/

development:
  secret_key_base: d0e8a0a4b25b228beafb9bf67a1907a59c32797b8ae6b3122a61425d9d78e4eb7076dc66ea4292b3932005efe62530623f90ef3ac1d024bdf0871086f3bb8707
  <<: *default
test:
  secret_key_base: e5a6c40516052e0084d3b24261f2d2fd2b06a3ec3a1c5a4b3fc3a7e8a4011cdedffe6020a5e8a14da50017f5f521d2cd4581d61dcccd1db0b625dc088c3f6fe5
  <<: *default
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *default
